# Mostly stolen from https://github.com/npostavs/emacs-travis/
language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=24.3
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26
    - EMACS_VERSION=master
  allow_failures:
    - env: EMACS_VERSION=master

install:
  - curl -LO https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export PATH=/tmp/emacs/bin:${PATH}

script:
  - emacs --version
  - make test

notifications:
  email: false
